# Generated by Django 3.2.9 on 2021-12-03 23:56

import customers.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', customers.models.CustomerManager()),
            ],
        ),
    ]
